update rc.local.patch

diff --git a/rc.local.patch b/rc.local.patch
--- a/rc.local.patch
+++ b/rc.local.patch
@@ -1,89 +1,95 @@
---- rc.local.orig	2017-06-26 11:25:50.172038160 +0200
-+++ rc.local.mod	2017-06-28 10:28:34.863708568 +0200
+--- rc.local.mod	2017-06-28 12:22:15.835050645 +0200
++++ rc.local.orig	2017-06-26 11:25:50.172038160 +0200
 @@ -1,4 +1,4 @@
--#!/bin/sh -e
-+#!/bin/bash
+-#!/bin/bash
++#!/bin/sh -e
  #
  # rc.local
  #
-@@ -11,7 +11,21 @@
+@@ -11,72 +11,19 @@
  #
  # By default this script does nothing.
  
--# assume there is no /etc/hostip until we have run at least once
-+set -e
+-set -e
+-
+-readonly SCRIPT_NAME=$(basename $0)
+-
+-log() {
+-  echo "$@"
+-  logger -p user.notice -t $SCRIPT_NAME "$@"
+-}
+-
+-err() {
+-  echo "$@" >&2
+-  logger -p user.error -t $SCRIPT_NAME "$@"
+-}
+-
+-log "Init networking"
+-ldconfig
+-insserv networking 2>/dev/null
+-rm /etc/ssh/ssh_host_* && dpkg-reconfigure openssh-server
+-systemctl enable ssh
+-
+-log "Fix NTP in case we are using built-in wifi"
+-iptables -t mangle -I POSTROUTING 1 -o wlan0 -p udp --dport 123 -j TOS --set-tos 0x00
+- 
+-log "Add ola user with password 'openlighting'"
+-useradd ola -m -G adm,dialout,sudo,plugdev,users,input,netdev,spi,i2c,gpio
+-echo "ola:openlighting" | chpasswd
+-
+-log "Change owner of ola's home directory since it was created before the user"
+-chown -R ola:ola /home/ola
+-
+-log "Update Raspbian"
+-apt-get -y update
+-
+-log "Upgrade RAspbian"
+-apt-get -y --force-yes upgrade
+-
+-log "Cleaning packages"
+-apt-get autoclean
+-apt-get clean
+-
+-log "Installing dependencies for OLA"
+-apt-get -y install libcppunit-dev libcppunit-1.13-0 uuid-dev pkg-config \
+-	libncurses5-dev libtool autoconf automake g++ libmicrohttpd-dev \
+-	libmicrohttpd10 protobuf-compiler libprotobuf-lite9 python-protobuf \
+-	libprotobuf-dev zlib1g-dev bison flex make libftdi-dev libftdi1 \
+-	libusb-1.0-0-dev liblo-dev libavahi-client-dev avahi-daemon libprotoc-dev \
+-	python2.7-numpy
+-
+-log "Modify dns resolver"
+-echo "nameserver 208.67.222.222" > /etc/resolv.conf
+-
+-log "Compile OLA"
+-cd /home/ola/ola
+-su ola -c "autoreconf -i" || (err "autoreconf failed" && exit 1)
+-su ola -c "./configure --enable-rdm-tests" || (err "configure failed, see /home/ola/ola/config.log" && exit 1)
+-su ola -c "make -j4" || (err "make failed" && exit 1)
+-su ola -c "make check" || (err "make check failed" && exit 1)
+-make install || (err "make install failed" && exit 1)
+-ldconfig || (err "ldconfig failed" && exit 1)
+-
+-log "Enable olad service"
+-systemctl enable olad || (err "systemctl failed" && exit 1)
+-
+-log "Replace this one time script with the final version"
+-rm -f /etc/rc.local
+-mv /etc/rc.local.final /etc/rc.local
+-reboot
++# assume there is no /etc/hostip until we have run at least once
++if [ ! -f /etc/hostip ]; then
++    # once-off initialization
++    echo "Welcome to Raspberry Pi - one-off initialization"
++    [ -x /sbin/ldconfig ] && /sbin/ldconfig
++    [ -x /sbin/insserv ] && /sbin/insserv networking 2>/dev/null
++    rm /etc/ssh/ssh_host_* && dpkg-reconfigure openssh-server
++fi
 +
-+readonly SCRIPT_NAME=$(basename $0)
-+
-+log() {
-+  echo "$@"
-+  logger -p user.notice -t $SCRIPT_NAME "$@"
-+}
-+
-+err() {
-+  echo "$@" >&2
-+  logger -p user.error -t $SCRIPT_NAME "$@"
-+}
-+
-+# Assume there is no /etc/hostip until we have run at least once
- if [ ! -f /etc/hostip ]; then
-     # once-off initialization
-     echo "Welcome to Raspberry Pi - one-off initialization"
-@@ -20,10 +34,52 @@
-     rm /etc/ssh/ssh_host_* && dpkg-reconfigure openssh-server
- fi
- 
--# Print the IP address
--if hostname -I > /etc/hostip; then
--  _IP=`cat /etc/hostip`
--  [ -z "$_IP" ] || echo "My network IP address is $_IP"
--fi
-+log "Fix NTP in case we are using built-in wifi"
-+iptables -t mangle -I POSTROUTING 1 -o wlan0 -p udp --dport 123 -j TOS --set-tos 0x00
-+ 
-+log "Add ola user with password 'openlighting'"
-+useradd ola -m -G adm,dialout,sudo,plugdev,users,input,netdev,spi,i2c,gpio
-+echo "ola:openlighting" | chpasswd
-+
-+log "Change owner of ola's home directory since it was created before the user"
-+chown -R ola:ola /home/ola
-+
-+log "Update Raspbian"
-+apt-get -y update
-+
-+log "Upgrade RAspbian"
-+apt-get -y --force-yes upgrade
-+
-+log "Cleaning packages"
-+apt-get autoclean
-+apt-get clean
-+
-+log "Installing dependencies for OLA"
-+apt-get -y install libcppunit-dev libcppunit-1.13-0 uuid-dev pkg-config \
-+	libncurses5-dev libtool autoconf automake g++ libmicrohttpd-dev \
-+	libmicrohttpd10 protobuf-compiler libprotobuf-lite9 python-protobuf \
-+	libprotobuf-dev zlib1g-dev bison flex make libftdi-dev libftdi1 \
-+	libusb-1.0-0-dev liblo-dev libavahi-client-dev avahi-daemon libprotoc-dev \
-+	python2.7-numpy
-+
-+log "Modify dns resolver"
-+echo "nameserver 208.67.222.222" > /etc/resolv.conf
-+
-+log "Compile OLA"
-+cd /home/ola/ola
-+su ola -c "autoreconf -i" || (err "autoreconf failed" && exit 1)
-+su ola -c "./configure --enable-rdm-tests" || (err "configure failed, see /home/ola/ola/config.log" && exit 1)
-+su ola -c "make -j4" || (err "make failed" && exit 1)
-+su ola -c "make check" || (err "make check failed" && exit 1)
-+make install || (err "make install failed" && exit 1)
-+ldconfig || (err "ldconfig failed" && exit 1)
-+
-+log "Enable olad service"
-+systemctl enable olad || (err "systemctl failed" && exit 1)
-+
-+log "Replace this one time script with the final version"
-+rm -f /etc/rc.local
-+mv /etc/rc.local.final /etc/rc.local
-+reboot
++# Print the IP address
++if hostname -I > /etc/hostip; then
++  _IP=`cat /etc/hostip`
++  [ -z "$_IP" ] || echo "My network IP address is $_IP"
++fi
  
  exit 0
